### ISSUE TITLE
[Technical Paper] Orderbook Connection (XIP1)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/docs#26]
### XIP1 🥇 
This Exchange Union Improvement Proposal (XIP) intends to simplify integration of `xud` for Exchanges, mainly the `gRPC` API.

*To be discussed:*
Who does matching? `XUD` or `XChange` ? In order to be able to do market orders, global view on `XChange` needed. Downside: more integration work for exchange.

1. Orderbook matching engine `xud` (`peerOrders`) vs. Xchange (`ownOrders`):

**a) Match of `ownOrder` from incoming `peerOrder` from outside**
XChange calls `fillOrder` (?) API for particular `peerOrder` ID on `xud` to request filling this order. Main problem: What happens to the XChange's internal order in between the swap: tbd

**b) Match of `ownOrder` from incoming `ownOrder` of XChange platform**
XChange calls `cancelOrder` API on `xud`. `xud` broadcasts removed order to it's peers.
**TBD:** How can this fail? What if Xchange doesn't call `cancelOrder` reliably?

**c) Match of `peerOrder` from incoming `ownOrder` of XChange platform**
Xchange constantly consumes all orders & updates via *callbacks* from the `getOrder` API (or `syncOrder` API, see comment below) and actually matches ALL orders via XChange platform's own matching engine. Orders need be classified as `ownOrder` or `peerOrder` within XChange matching engine. This 'global view' of orders is needed to do e.g. market orders. After successful swap is completed, `xud` removes order from `xud` orderbook.

**d) No Match of `ownOrder` with `ownOrder` or `peerOrder` on XChange platform**
`placeOrder` on `xud`. `xud` then broadcasts to other `xud` peers.

Todo:
- Add callback to `getOrders` api OR leave it (might be useful) and expose new `syncOrders` API for constant callback of `peerOrder` updates
- Add Callback to place an order on `Xchange` via 'XUD' user account
- `cancelOrder` API on `xud`
- All APIs should have a success/error callback for Xchange
-  `xud` should take over OrderIDs from Xchange system (at the moment it's only `xud`s genererated `uuidv1()`, which can be kept, but as soon as an order gets into XChange platform, it should carry XChange platform's orderID within `xud`)

2. Who is Maker who is Taker?
Each `xud` according to it's local view. If both `xud`s try to be takers to potentially save fees, no swap happens. See https://exchangeunion.slack.com/archives/C9U3E0UQK/p1523458833000822\

3. Payment channel volume check:
Total payment channel volume check, pre-filter `peerOrder`s based on overall payment channel volume

**Comment by moshababo** [comment]
> a) Match of ownOrder from incoming peerOrder from outside
xud has a 'XUD' user account (with some special rights) on the XChange platform and uses existing 'fill order' methods to reserve the order at XChange platform for an incoming swap trying to fill this ownOrder. XChange hands over -> order -> to xud. After successful swap, remove order from xud orderbook.
TBD: What if the swap fails? Biggest issue with this concept. Order has already been filled on Xchange in that moment, thus 'responsibility' is with xud. Definitely not part of pre-alpha.

It sounds like you describing an `xud` -> `XChange` control flow, but obviously it should always be that `XChange` is the client, and `xud` is the server. So any accounts/credentials for `xud`, in addition to subscribing to events, is up to `XChange`. 

If I understood you correctly, you're describing this:
1) `XChange` placing an order on `xud`
2) `xud` found a successful match, alerting `XChange`, which updates the order status to _filled_.
3) `xud` attempts a swap, that can fail.

So you're having a problem with the _filled_ order state on `XChange`, in case of a swap failure. 
But this state is reliable only if the match was local, where it can be derive from the synchronous response to `placeorder` (so you can effectively not list the order on `XChange` until you're getting a response). 
If the match occurred remotely, so even if we'll make the peer transmit the matching event prior to swap execution, then it's async anyway, and so it can't save `XChange` from having a stale order states, in case it will want to enlist it too. 

> b) Match of ownOrder from incoming ownOrder of XChange platform
XChange calls cancelOrder API on xud
TBD: How can this fail? What if Xchange doesn't call cancelOrder reliably?

`cancelOrder` isn't going to be very reliable anyway, because if the match didn't occur immediately (when doing `placeorder`), then the order will be broadcasted, and so the order cancellation will need to happen effectively over the P2P network. This makes this situation similar to a race condition between peers, just that no swap is involved. 

> c) Match of peerOrder from incoming ownOrder of XChange platform
Xchange constantly consumes all orders & updates via callbacks from the getOrder API (or syncOrder API, see comment below) and actually matches ALL orders via XChange platform's own matching engine. Orders need be classified as ownOrder or peerOrder within XChange matching engine. This 'global view' of orders is needed to do e.g. market orders. After successful swap is completed, xud removes order from xud orderbook.

Why would you want `XChange` to do matching on `peerOrders`? and in this case, would you want that the matching will be solely on `XChange`, so that `xud` role will only be to listen for to peers and execute swaps?

> * Add callback to getOrders api OR leave it (might be useful) and expose new syncOrders API for constant callback of peerOrder updates

`getOrders` seems to me just like a sanity call for now, to know what's in `xud`.`XChange` should know all about the `ownOrders` in `xud` anyway, so yes, I would suggest to just adding `syncPeerOrders`, which will stream incoming orders from the P2P network.

> * Add Callback to trigger 'fillOrder' on Xchange vis 'XUD' user account

`fillOrder` is in the context of `XChange`, so i don't think that `xud` should use this terminology. `xud` only knows about a match / swap. If match occurs locally, it will be the response to `placeorder`. If it will occur on a remote node, we can use an event name like `remoteOrderMatch` or `asyncOrderMatch`.

**Comment by kilrau** [comment]
> It sounds like you describing an `xud` -> `XChange` control flow, but obviously it should always be that `XChange` is the client, and `xud` is the server. So any accounts/credentials for `xud`, in addition to subscribing to events, is up to `XChange`. 

Well the point is that an Exchange needs to actively implement sth for the control flow to be `XChange` -> `xud`. Just opening a user account on `XChange` wouldn't require `XChange` to do anything special. That's why I thought about it. I'll explain it in more detail tmrw in the call and you can give me feedback.

> If I understood you correctly, you're describing this:
> 1) `XChange` placing an order on `xud`
> 2) `xud` found a successful match, alerting `XChange`, which updates the order status to _filled_.
> 3) `xud` attempts a swap, that can fail.
> 
> 

> So you're having a problem with the _filled_ order state on `XChange`, in case of a swap failure. 
> But this state is reliable only if the match was local, where it can be derive from the synchronous response to `placeorder` (so you can effectively not list the order on `XChange` until you're getting a response). 
> If the match occurred remotely, so even if we'll make the peer transmit the matching event prior to swap execution, then it's async anyway, and so it can't save `XChange` from having a stale order states, in case it will want to enlist it too. 

All correct. Please help me think more about what we possibly could do here. @moshababo @sangaman @itsbalamurali 

> > c) Match of peerOrder from incoming ownOrder of XChange platform
> Xchange constantly consumes all orders & updates via callbacks from the getOrder API (or syncOrder API, see comment below) and actually matches ALL orders via XChange platform's own matching engine. Orders need be classified as ownOrder or peerOrder within XChange matching engine. This 'global view' of orders is needed to do e.g. market orders. After successful swap is completed, xud removes order from xud orderbook.
> 
> Why would you want `XChange` to do matching on `peerOrders`? and in this case, would you want that the matching will be solely on `XChange`, so that `xud` role will only be to listen for to peers and execute swaps?

Well simply because `XChange` needs one global order book view (e.g. to do market orders). We'll go through it in the call too.

> > * Add Callback to trigger 'fillOrder' on Xchange vis 'XUD' user account
> 
> `fillOrder` is in the context of `XChange`, so i don't think that `xud` should use this terminology.

Agree, changed the name.

**Comment by kilrau** [comment]
Changed `cancelOrder` to `removeOrder` as per https://github.com/ExchangeUnion/xud/issues/121

**Comment by moshababo** [comment]
> Well the point is that an Exchange needs to actively implement sth for the control flow to be XChange -> xud. Just opening a user account on XChange wouldn't require XChange to do anything special. That's why I thought about it. I'll explain it in more detail tmrw in the call and you can give me feedback.

I don't think that the Exchange can or should be passive on that part. There would be some decisions to make on how to integrate with `xud`. And even if all what it comes down to is one simple callback that `xud` can invoke, it will still be more complicated to attempt to inverse the control.

> All correct. Please help me think more about what we possibly could do here. @moshababo @sangaman @itsbalamurali 

You have either one of two problems:
1) match was found on `xud`. order was unfilled on `XChange`, so It set it now to _filled_, but then swap failed on `xud`. In this case `xud` can just alert this, and `XChange` will reopen the order once again. Not a serious issue.

2) match was found on `xud`, but order was already filled on `XChange`. It happened because the order cancellation didn't propagate `xud` & the P2P network fast enough. What we can do is to add a call after every remote match, to verify that the order is still valid. But even so, it can get invalidated between the response we'll get and the swap instantiation. This means that we must be able to handle swaps on an invalid order, hence to make it fail gracefully. This situation will also happen in case of race condition between peers, but in this case LND/Raiden won't even get involved, so we can't rely on a swap to invalidate another swap.

> Well simply because XChange needs one global order book view (e.g. to do market orders). We'll go through it in the call too.

If `XChange` needs a global order book view, it can simply listen to to `peerOrders`, but let `xud` do the matching. If these orders would be matched on `XChange`, there's no purpose to `xud` matching.

**Comment by moshababo** [comment]
`cancelOrder` is for the Exchange-facing API (gRPC). it will trigger `removeOrder` on the local order book API, and in addition will invalidate the order over the P2P network. 
So I think that the terminology was actually fine.

**Comment by michael1011** [comment]
> xud should take over OrderIDs from Xchange system (at the moment it's only xuds genererated uuidv1(), which can be kept, but as soon as an order gets into XChange platform, it should carry XChange platform's orderID within xud)

It don't think `xud` should interfere with the ID system of the XChange. They can add a separate ID to the order internally if they want to but `xud` should only use its own IDs to ensure that all nodes are compatible with each other.

> match was found on xud. order was unfilled on XChange, so It set it now to filled, but then swap failed on xud. In this case xud can just alert this, and XChange will reopen the order once again. Not a serious issue.

What about a `pending` state? If the swap fails the XChange could set the state back to unfilled and if it is successful to filled. Users could get confused when their orders reappear suddenly. But this is up to the XChanges.

**Comment by kilrau** [comment]
> `cancelOrder` is for the Exchange-facing API (gRPC). it will trigger `removeOrder` on the local order book API, and in addition will invalidate the order over the P2P network. 
> So I think that the terminology was actually fine.

Got it, changed back.

**Comment by sangaman** [comment]
Sorry for being a bit late to the party.

> c) Match of peerOrder from incoming ownOrder of XChange platform
> Xchange constantly consumes all orders & updates via callbacks from the getOrder API (or syncOrder API, see comment below) and actually matches ALL orders via XChange platform's own matching engine. Orders need be classified as ownOrder or peerOrder within XChange matching engine. This 'global view' of orders is needed to do e.g. market orders. After successful swap is completed, xud removes order from xud orderbook.

This is a significant shift from how I was thinking we'd approach order matching. I think it's potentially a large change to expect exchanges to track all `peerOrders` internally. For new exchanges that are gearing up to use `xud` from the beginning, I think the better approach is actually to let `xud` handle ALL matching, including matches that are entirely internal.

I think the simplest approach for market orders - and I believe we discussed this approach in SF last month - the is to first attempt to fill the market order locally, guaranteeing instant execution if local orders are available. Let's discuss more complex approaches on the call.

> All correct. Please help me think more about what we possibly could do here. @moshababo @sangaman @itsbalamurali 

> What about a pending state? If the swap fails the XChange could set the state back to unfilled and if it is successful to filled. Users could get confused when their orders reappear suddenly. But this is up to the XChanges.

The pending state is certainly an option, as is canceling the order and recreating it if the swap fails, but I agree with @moshababo that this should ultimately be up to the exchange how to handle this. The same is probably true for how to handle market orders above, should they be filled locally only or should they attempt to execute swaps?

> If XChange needs a global order book view, it can simply listen to to peerOrders, but let xud do the matching. If these orders would be matched on XChange, there's no purpose to xud matching.

My feeling is that it doesn't make sense for the exchange to have a "copy" of the `xud` orders database, if that's what we're discussing. Rather than maintain its own copy, I think the exchange should just query for a set of the best orders available on either side of each book strictly for user-facing display/informational purposes, and can keep this up to date by listening to 'xud' for events when orders are added or removed from the books.

**Comment by kilrau** [comment]
Just talked with Moshe, please think about these 2 main problems and let's discuss it tomorrow:
1. `xud` doesn't do any matching, only `XChange` matches. Motivation: `XChange` needs to see all orders, including `peerOrders` to get the *best price* for market orders. This is our great promise.
2. Assuming only `XChange` matches, when `XChange` matched peer Order, `xud` picks up this order and tries to swap, but swap fails because `peerOrder` is already cancelled/filled by other peer. Update didn't broadcast fast enough to `XChange`. So far only one proposed solution: Pending state on `XChange`

**Comment by moshababo** [comment]
@kilrau, just to summarize things, in regards to the 2nd thing you mentioned:

We have 2 sides to the problem:
1) Order is getting into a `cancelled/pending/filled` state on `XChange`, but need to be changed back to `open` after a swap failure (either due to a technical problem or because maker order is no longer valid). 
2) Ensuring that if the maker order is no longer valid, the swap will fail, and with less damage as possible (locked funds, etc.). This applies both to swap that should fail due to a preceding swap (by other peer), and also to a swap on an order that was matched internally by a remote `XChange` - so there's no preceding swap to rely on.

**Comment by moshababo** [comment]
@kilrau @sangaman 

To get best price, matching engine should be aware of all available orders. 
The Exchange will need to know about `peerOrders` to match with best price, but perhaps also for showing the orders on the platform. Querying `xud` on each match is not viable, so the Exchange will need to sync all `peerOrders`. If the Exchange will find better prices on `peerOrders`, it will place his order on `xud`. At that point there's no reason for `xud` to do matching again, because the Exchange already knows all the match information, which can be sent to `xud` to trigger a swap. 
Ultimately, we'll want all matching to be done only in one place. It doesn't matter if it's on the Exchange or on `xud`. But since existing exchanges already have their own infrastructure, we can't rely on them to pass everything to `xud`.

`xud` matching engine currently supports all matching - `ownOrders` with `peerOrders`, and `ownOrders` with `ownOrders`. That's the kind of matching that the exchanges will need to implement. If we'll want to save some work for them, and give them a matching engine module that will be used instead of theirs (if they have any), there's no reason why that module won't be `xud` itself, activated on a matching mode. I don't think that implementing the matching engine as a separate stand-alone service makes much sense. 

So I think that `xud` should either do no matching, or all matching. This way we can offer a flexible integration options for different players on the market. Exchanges will either need to implement new logic on their existing infrastructure, or to pass everything to `xud`. Something in the middle won't work. The white-label exchange (`XChange`) will probably want to use the 2nd option. In this case, `peerOrders` might need to be synced anyway, to show orders on the platform.

**Comment by sangaman** [comment]
Before having read @moshababo's post above, here are my thoughts after our talk yesterday with respect to how `xud` could handle "global market" order matching.

1. The exchange must keep `xud` up to date with `OwnOrders`. To the extent that it falls out of sync, there's the possibility that it won't match with the best orders, 

2. The exchange calls a streaming API endpoint for a global market order.

3. `xud` sorts both peer and own orders on the opposite side of the given trading pair (the actual sorting is done continuously via priority queues) and selects the orders  with the best price that must be taken to fill the market order.

4. `xud` sums up the quantity of selected own orders from step 3 above and sends this information to the exchange immediately. The exchange can then execute a local/internal market order for this amount.

5. `xud` marks all the selected peer orders from step 3 as pending and attempts to execute the swap for each one. 

6. Anytime a swap either executes successfully or fails, the exchange is notified of this result over the streaming response from step 2.

7. Once all swaps have either executed or failed, the streaming response is closed.

As an example, if the exchange wants to sell 10 bitcoin for litecoin and the orderbooks are like so:

| Price | Quantity | Type |
| ----- | -----------| -----|
| 100 LTC/BTC | 2 BTC | Own |
| 90 LTC/BTC | 5 BTC | Peer |
| 80 LTC/BTC | 3 BTC | Own |
| 70 LTC/BTC | 5 BTC | Peer |
| 70 LTC/BTC | 5 BTC | Own |

Xud would first return a quantity of 5 BTC, telling the exchange to market sell 5 bitcoin right away, which would fill the two own orders at 100 and 80 LTC/BTC. Then it would attempt to swap the 5 BTC at 90 LTC each peer order and alert the exchange once the swap has failed or completed. The orders for 70 LTC/BTC are not touched.

Let me know your thoughts.

**Comment by moshababo** [comment]
I think it's a good idea to scope the placing of a market order under one streaming call. We could use it for limit orders as well, scoping the swap execution wheres it's the taker order (same as in market order), and finalizing the call if the order becomes a maker order. 

Besides that, it looks like you're offering that `xud` will do all matching (including internal matching). This could solve the "best price" problem, but i'm not sure that all exchanges will want `xud` to replace their own existing matching engine. 
It could also technically work if both the exchange and `xud` will do internal matching, but I think it will create more problems in syncing between them, and a confusion as to how to use `xud`.

**Comment by sangaman** [comment]
I don't think we'd need to replace the internal matching engine, I'm thinking that in response to a global market order that will at least partly be filled internally, xud should tell the exchange to fill X quantity via a regular internal market order. So xud is not exactly matching internal orders, rather it sees how much of a given global market order should be filled internally and lets the exchange fill that amount internally. The exchange is ultimately responsible for which exact internal orders get filled.

In case xud falls out of sync with the internal orderbook, it may not necessarily get the best price because it will be prioritizing based on stale data. But it won't attempt to fill a non-existent internal order, for instance.

**Comment by offerm** [comment]
My 2 cents:

First about Market orders - As far as I know there are no pure market orders anymore. according to regulation exchanges need to convert market order to stop/limit orders to prevent wild execution. There should always be a limit.

Second - IMHO, from the exchange POV, XUD is an upstream exchange. The exchange has an interface allowing it to query status, send order, deleted orders and get execution notifications.  Internal trading (matches at the exchange level) should nor involve XUD. Likewise, XUD matches should not involve the exchange and just inform the exchange on successful/partial execution. 

The exchange should have full flexibility to decide which orders to send XUD. These orders do not need to match 1:1 the orders on the exchange.

**Comment by sangaman** [comment]
> As far as I know there are no pure market orders anymore. according to regulation exchanges need to convert market order to stop/limit orders to prevent wild execution. There should always be a limit.

That's news to me. How do they know what price to set for the limit orders if a user doesn't specify one? I figure this would at least be different across exchanges and jurisdictions.

> The exchange should have full flexibility to decide which orders to send XUD. These orders do not need to match 1:1 the orders on the exchange.

In this case, xud would not be able to reliably determine the best global price. As I see it, finding the best price means there needs to be matching logic somewhere that's aware of both internal and remote orders, if that can't be xud then the exchange would need to track remote orders and find the best price themselves. This is basically what @kilrau was describing above I believe. I figure it's a burden on the exchanges, but maybe it's the best approach after all.

**Comment by moshababo** [comment]
Me and @sangaman discussed this, and reached an agreement that we should have only 2 modes: `xud` will do no matching, or all matching. Any other viable mode that we can add will be too similar to these ones, so there's no real reason to do that. 

We thought to represent that behavior by a boolean config value, `disableMatching`, which its default value will be `false`. That will also be the mode which we'll be focused on for now. 

@kilrau
